import 'bootstrap/dist/css/bootstrap.css'
import './globals.css'
import { Inter } from 'next/font/google'
import Navegation from '@/components/Navegation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Example nextjs react',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navegation />
        <div className='container p-4'>{children}</div>
      </body>
    </html>
  );
}
